sudo: false
dist: trusty
language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - WP_VERSION=latest

matrix:
  include:
    - php: 7.4
    - php: 7.3
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: nightly
  allow_failures:
    - php: nightly

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - php -m
  - |
    bash phpunit/install.sh wordpress_test root '' localhost $WP_VERSION
    composer global require "phpunit/phpunit=4.8.*|5.7.*"

script:
  - |
    phpunit
    WP_MULTISITE=1 phpunit
